apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-server
  namespace: mi-empresa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resource-server
  template:
    metadata:
      labels:
        app: resource-server
    spec:
      containers:
        - name: resource-server
          image: danst21/resource-server:45e0b66f51296265f9c6e8f3ea71c8635f5ddc14
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: resource-server-config
#            - secretRef:
#                name: resource-server-secrets   # variables sensibles
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"