name: CD — Tests + Build + Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # JOB 1 — Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Correr tests
        run: ./mvnw test

  # JOB 2 — Build y Push
  # needs: test significa que este job solo corre si test pasó
  build-and-push:
    runs-on: ubuntu-latest
    needs: test                    # depende de que test pase

    # Solo en push a main, no en pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build y Push imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/resource-server:latest
            ${{ secrets.DOCKER_USERNAME }}/resource-server:${{ github.sha }}

  update-k8s-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.G_TOKEN }}  # token automático de GitHub

      # Actualiza el tag de la imagen en deployment.yml
      - name: Actualizar imagen en deployment.yml
        run: |
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/resource-server:.*|image: ${{ secrets.DOCKER_USERNAME }}/resource-server:${{ github.sha }}|g" k8s/deployment.yml

      # Verifica el cambio
      - name: Verifica cambio
        run: grep "image:" k8s/deployment.yml

      # Commit y push del deployment.yml actualizado
      - name: Commit y Push manifiestos actualizados
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yml
          git commit -m "Update image to ${{ github.sha }}"
          git push
      # ArgoCD detecta este push y aplica el cambio automáticamente

  # JOB 3 — Deploy a Kubernetes
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build-and-push          # depende de que build-and-push pase
#
#    steps:
#      - name: Checkout código
#        uses: actions/checkout@v4
#
#      # Instala kubectl en el runner
#      - name: Setup kubectl
#        uses: azure/setup-kubectl@v3
#        with:
#          version: 'v1.28.0'
#
#      # Configura el acceso al cluster de Kubernetes
#      # KUBE_CONFIG es el contenido de tu ~/.kube/config en base64
#      - name: Configurar kubeconfig
#        run: |
#          mkdir -p ~/.kube
#          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
#
#      # Actualiza la imagen en el deployment
#      - name: Deploy a Kubernetes
#        run: |
#          kubectl set image deployment/resource-server \
#            resource-server=${{ secrets.DOCKER_USERNAME }}/resource-server:${{ github.sha }}
#
#      # Verifica que el rollout fue exitoso
#      - name: Verificar rollout
#        run: |
#          kubectl rollout status deployment/resource-server --timeout=300s